#include "stdwx.h"

// This file must come first.
#include "Strings.cpp"

#include "EruptionUI.cpp"
#include "ImageSetsVolcano.cpp"
#include "LogicResourceNameVolcano.cpp"
#include "LogicResourceTypeVolcano.cpp"
#include "LogicTileIsLandVolcano.cpp"
#include "LogicTileIsResourceVolcano.cpp"
#include "RuleChainVolcano.cpp"
#include "RuleCityReducedVolcano.cpp"
#include "RuleCornerDestroyedSingleBonus.cpp"
#include "RuleCornerDestroyedVolcano.cpp"
#include "RuleCornerDestroyedVolcanoCities.cpp"
#include "RuleGenerateVolcanoDesert.cpp"
#include "RuleInitializeVolcano.cpp"
#include "RuleInitializeVolcanoCities.cpp"
#include "RulePlaceCityVolcanoCities.cpp"
#include "RuleReduceCityVolcanoCities.cpp"
#include "RuleRestartVolcanoMetropolis.cpp"
#include "RuleRewardHiddenTileVolcano.cpp"
#include "RuleSelectVolcanoMetropolis.cpp"
#include "RuleVolcano.cpp"
#include "VolcanoCitiesOption.cpp"
#include "VolcanoDesertName.cpp"
#include "VolcanoDesertOption.cpp"
#include "VolcanoHiddenTilesOption.cpp"
#include "VolcanoKeyMaps.cpp"
#include "VolcanoName.cpp"
#include "VolcanoRules.cpp"
#include "VolcanoSingleBonusOption.cpp"
#include "VolcanoSingleBonusStats.cpp"
#include "VolcanoStats.cpp"
#include "VolcanoUI.cpp"
