REM wxWidgets dlls
copy "..\wxWidgets\2.8.10\lib\vc_dll\wxbase28u_net_vc_custom.dll" distribute
copy "..\wxWidgets\2.8.10\lib\vc_dll\wxbase28u_vc_custom.dll" distribute
copy "..\wxWidgets\2.8.10\lib\vc_dll\wxbase28u_xml_vc_custom.dll" distribute
copy "..\wxWidgets\2.8.10\lib\vc_dll\wxmsw28u_adv_vc_custom.dll" distribute
copy "..\wxWidgets\2.8.10\lib\vc_dll\wxmsw28u_aui_vc_custom.dll" distribute
copy "..\wxWidgets\2.8.10\lib\vc_dll\wxmsw28u_core_vc_custom.dll" distribute
copy "..\wxWidgets\2.8.10\lib\vc_dll\wxmsw28u_gl_vc_custom.dll" distribute
copy "..\wxWidgets\2.8.10\lib\vc_dll\wxmsw28u_html_vc_custom.dll" distribute
copy "..\wxWidgets\2.8.10\lib\vc_dll\wxbase28ud_net_vc_custom.dll" distribute
copy "..\wxWidgets\2.8.10\lib\vc_dll\wxbase28ud_vc_custom.dll" distribute
copy "..\wxWidgets\2.8.10\lib\vc_dll\wxbase28ud_xml_vc_custom.dll" distribute
copy "..\wxWidgets\2.8.10\lib\vc_dll\wxmsw28ud_adv_vc_custom.dll" distribute
copy "..\wxWidgets\2.8.10\lib\vc_dll\wxmsw28ud_aui_vc_custom.dll" distribute
copy "..\wxWidgets\2.8.10\lib\vc_dll\wxmsw28ud_core_vc_custom.dll" distribute
copy "..\wxWidgets\2.8.10\lib\vc_dll\wxmsw28ud_gl_vc_custom.dll" distribute
copy "..\wxWidgets\2.8.10\lib\vc_dll\wxmsw28ud_html_vc_custom.dll" distribute

REM fmod dll
copy "..\fmod\3.7.4-win\api\fmod.dll" distribute
